import {supabase} from '../lib/supabase';import type {Event,LineMessage,Member,Task} from '../types';
const must=()=>{if(!supabase)throw new Error('Supabase is unavailable in fixture mode');return supabase};
const task=(r:Record<string,unknown>):Task=>({id:String(r.id),title:String(r.title),description:String(r.description||''),status:r.status as Task['status'],priority:r.priority as Task['priority'],assigneeId:r.assignee_id?String(r.assignee_id):undefined,dueDate:r.due_date?String(r.due_date):undefined,eventId:r.event_id?String(r.event_id):undefined,sourceType:r.source_type as Task['sourceType'],sourceId:r.source_id?String(r.source_id):undefined,createdAt:String(r.created_at),completedAt:r.completed_at?String(r.completed_at):undefined});
const event=(r:Record<string,unknown>):Event=>({id:String(r.id),title:String(r.title),description:String(r.description||''),location:String(r.location||''),startAt:String(r.start_at),endAt:String(r.end_at),allDay:Boolean(r.all_day),members:Array.isArray(r.event_members)?r.event_members.map((x:Record<string,unknown>)=>String(x.member_id)):[],sourceType:r.source_type as Event['sourceType'],sourceId:r.source_id?String(r.source_id):undefined,googleCalendarEventId:r.google_calendar_event_id?String(r.google_calendar_event_id):undefined,googleSyncStatus:r.google_sync_status as Event['googleSyncStatus']});
export async function loadTasks(communityId:string){const {data,error}=await must().from('tasks').select('*').eq('community_id',communityId);if(error)throw error;return (data||[]).map(task)}
export async function loadEvents(communityId:string){const {data,error}=await must().from('events').select('*,event_members(member_id)').eq('community_id',communityId);if(error)throw error;return (data||[]).map(event)}
export async function loadWorkspace(){const db=must();const {data:bootstrap,error:bootstrapError}=await db.rpc('bootstrap_current_user',{p_display_name:null});if(bootstrapError)throw new Error(`BOOTSTRAP_FAILED:${bootstrapError.code||"DATABASE_ERROR"}`,{cause:bootstrapError});if(!bootstrap?.length)throw new Error('NOT_INVITED');const {data:membership,error:me}=await db.from('community_members').select('id,community_id,role,active,profiles!inner(id,display_name,avatar_url,auth_user_id)').eq('profiles.auth_user_id',(await db.auth.getUser()).data.user?.id||'').eq('active',true).maybeSingle();if(me)throw me;if(!membership)throw new Error('NOT_INVITED');const cid=membership.community_id;const [ts,es,ms,ls]=await Promise.all([db.from('tasks').select('*').eq('community_id',cid),db.from('events').select('*,event_members(member_id)').eq('community_id',cid),db.from('community_members').select('id,role,active,profiles!inner(display_name,avatar_url,auth_user_id)').eq('community_id',cid),db.from('line_messages').select('*,line_groups(display_name),line_users(display_name)').eq('community_id',cid).order('received_at',{ascending:false})]);for(const x of [ts,es,ms,ls])if(x.error)throw x.error;const ownProfile=membership.profiles as unknown as Record<string,unknown>;return {communityId:cid,currentProfileId:String(ownProfile.id),currentMemberId:membership.id,role:membership.role as Member['role'],tasks:(ts.data||[]).map(task),events:(es.data||[]).map(event),members:(ms.data||[]).map((r)=>{const p=r.profiles as unknown as Record<string,unknown>;return {id:r.id,displayName:String(p.display_name),email:'',role:r.role as Member['role'],active:r.active,avatar:String(p.display_name||'?').slice(0,1)};}),messages:(ls.data||[]).map((r)=>({id:r.id,group:String((r.line_groups as unknown as Record<string,unknown>)?.display_name||'LINE Group'),sender:String((r.line_users as unknown as Record<string,unknown>)?.display_name||'Unknown'),text:r.text||'',receivedAt:r.received_at,status:r.status} as LineMessage))};}
export async function createTask(cid:string,profileId:string,x:Omit<Task,'id'|'createdAt'>){const {data,error}=await must().from('tasks').insert({community_id:cid,title:x.title,description:x.description,status:x.status,priority:x.priority,assignee_id:x.assigneeId||null,due_date:x.dueDate||null,event_id:x.eventId||null,source_type:x.sourceType,source_id:x.sourceId||null,created_by:profileId}).select().single();if(error)throw error;return task(data)}
export async function patchTask(id:string,x:Partial<Task>){const payload:Record<string,unknown>={};const map:Record<string,string>={title:'title',description:'description',status:'status',priority:'priority',assigneeId:'assignee_id',dueDate:'due_date',eventId:'event_id',completedAt:'completed_at'};for(const [k,v] of Object.entries(x))if(map[k])payload[map[k]]=v??null;const {data,error}=await must().from('tasks').update(payload).eq('id',id).select().single();if(error)throw error;return task(data)}
export async function deleteTask(id:string){const {error}=await must().from('tasks').delete().eq('id',id);if(error)throw error}
async function invokeSync(id:string,operation:string){const {error}=await must().functions.invoke('google-calendar-sync',{body:{eventId:id,operation}});if(error){await must().from('events').update({google_sync_status:'error'}).eq('id',id);throw error}}
export async function createEvent(cid:string,profileId:string,x:Omit<Event,'id'>){const {data,error}=await must().from('events').insert({community_id:cid,title:x.title,description:x.description,location:x.location,start_at:x.startAt,end_at:x.endAt,all_day:x.allDay,created_by:profileId,google_sync_status:'pending'}).select().single();if(error)throw error;if(x.members.length)await must().from('event_members').insert(x.members.map(member_id=>({event_id:data.id,member_id})));await invokeSync(data.id,'create');return event(data)}
export async function patchEvent(id:string,x:Partial<Event>){const payload:Record<string,unknown>={};const map:Record<string,string>={title:'title',description:'description',location:'location',startAt:'start_at',endAt:'end_at',allDay:'all_day'};for(const [k,v] of Object.entries(x))if(map[k])payload[map[k]]=v;const {data,error}=await must().from('events').update({...payload,google_sync_status:'pending'}).eq('id',id).select().single();if(error)throw error;await invokeSync(id,'update');return event(data)}
export async function deleteEvent(id:string){await invokeSync(id,'delete')}
export async function retryEvent(id:string){await invokeSync(id,'upsert')}
export async function convertLineMessage(messageId:string,kind:'task'|'event',payload:Record<string,unknown>){const {data,error}=await must().rpc(kind==='task'?'convert_line_message_to_task':'convert_line_message_to_event',{p_message_id:messageId,p_payload:payload});if(error)throw error;return data}
export async function setMessageStatus(id:string,status:LineMessage['status']){const {error}=await must().from('line_messages').update({status}).eq('id',id);if(error)throw error}
