import {assertEquals,assertRejects} from 'https://deno.land/std@0.224.0/assert/mod.ts';
import {extractOpenAiOutput,ProviderError,requestOpenAi} from './provider.ts';
import type {StructuredAiResponse} from './schema.ts';

const message={type:'message',content:'確認しました',title:null,summary:null,actions:[]} satisfies StructuredAiResponse;
const payload={title:'準備',description:null,status:'todo' as const,priority:'medium' as const,assignee_id:null,due_date:null};
const proposal={type:'proposal',content:null,title:'Task proposal',summary:'整理します',actions:[{kind:'create_task',target:'task',payload}]} satisfies StructuredAiResponse;
const response=(value:unknown,extra:Record<string,unknown>={})=>({id:'resp_fixture',object:'response',status:'completed',output:[{id:'msg_fixture',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',annotations:[],text:JSON.stringify({response:value})}]}],usage:{input_tokens:12,output_tokens:4},...extra});
const fetcher=(body:unknown)=>(()=>Promise.resolve(new Response(JSON.stringify(body),{status:200}))) as typeof fetch;

Deno.test('extracts the exact Responses API output_text shape for a message',()=>assertEquals(extractOpenAiOutput(response(message)),message));
Deno.test('extracts and validates a proposal response',()=>assertEquals(extractOpenAiOutput(response(proposal)),proposal));
Deno.test('provider returns structured response and usage',async()=>{Deno.env.set('OPENAI_API_KEY','test-only');const result=await requestOpenAi('context',fetcher(response(message)));assertEquals(result.response,message);assertEquals(result.inputTokens,12);assertEquals(result.outputTokens,4)});
Deno.test('provider classifies rate limits',async()=>{Deno.env.set('OPENAI_API_KEY','test-only');const rateLimited=(()=>Promise.resolve(new Response('',{status:429}))) as typeof fetch;await assertRejects(()=>requestOpenAi('context',rateLimited),ProviderError,'RATE_LIMIT')});
Deno.test('provider bounds transient 5xx retries to two attempts',async()=>{Deno.env.set('OPENAI_API_KEY','test-only');let calls=0;const unavailable=(()=>{calls++;return Promise.resolve(new Response('',{status:503}))}) as typeof fetch;await assertRejects(()=>requestOpenAi('context',unavailable),ProviderError,'PROVIDER_UNAVAILABLE');assertEquals(calls,2)});
Deno.test('provider classifies network and timeout-style fetch failures without leaking errors',async()=>{Deno.env.set('OPENAI_API_KEY','test-only');let calls=0;const unavailable=(()=>{calls++;return Promise.reject(new Error('sensitive network detail'))}) as typeof fetch;const error=await assertRejects(()=>requestOpenAi('context',unavailable),ProviderError,'PROVIDER_UNAVAILABLE');assertEquals(calls,2);assertEquals(error.diagnostic,undefined)});
Deno.test('rejects malformed JSON at the parse stage without retaining text',async()=>{const body=response(message);((body.output[0].content[0]) as {text:string}).text='{';const error=await assertRejects(async()=>extractOpenAiOutput(body),ProviderError,'INVALID_STRUCTURED_RESPONSE');assertEquals(error.diagnostic?.stage,'json_parse');assertEquals('text'in (error.diagnostic||{}),false)});
Deno.test('rejects missing required fields with safe Zod paths',async()=>{const error=await assertRejects(async()=>extractOpenAiOutput(response({type:'message',content:'x'})),ProviderError);assertEquals(error.diagnostic?.stage,'zod_validation');assertEquals(error.diagnostic?.issues?.some(issue=>issue.path==='response.actions'),true)});
Deno.test('rejects unknown action kinds',async()=>{const error=await assertRejects(async()=>extractOpenAiOutput(response({...proposal,actions:[{...proposal.actions[0],kind:'delete_everything'}]})),ProviderError);assertEquals(error.diagnostic?.stage,'zod_validation')});
Deno.test('rejects invalid payload UUIDs',async()=>{const invalid={...proposal,actions:[{...proposal.actions[0],payload:{...payload,assignee_id:'not-a-uuid'}}]};const error=await assertRejects(async()=>extractOpenAiOutput(response(invalid)),ProviderError);assertEquals(error.diagnostic?.issues?.some(issue=>issue.path==='response.actions.0.payload.assignee_id'),true)});
Deno.test('classifies incomplete output before attempting JSON parsing',async()=>{const error=await assertRejects(async()=>extractOpenAiOutput(response(message,{status:'incomplete',incomplete_details:{reason:'max_output_tokens'}})),ProviderError);assertEquals(error.diagnostic?.stage,'response_incomplete');assertEquals(error.diagnostic?.incompleteReason,'max_output_tokens')});
Deno.test('classifies refusal without logging refusal text',async()=>{const body=response(message);body.output[0].content=[{type:'refusal',annotations:[],text:'sensitive refusal'}];const error=await assertRejects(async()=>extractOpenAiOutput(body),ProviderError);assertEquals(error.diagnostic?.stage,'response_refusal');assertEquals(JSON.stringify(error.diagnostic).includes('sensitive refusal'),false)});
