import {supabase} from '../lib/supabase';
import type {Json} from '../types/database';

export type ConversationSession={id:string;communityId:string;profileId:string;goalId?:string;title:string;status:'active'|'archived';createdAt:string;updatedAt:string};
export type ConversationMessage={id:string;communityId:string;sessionId:string;role:'user'|'assistant'|'system';content:string;reasoningSummary?:string;proposal?:Json;proposalStatus:'none'|'proposal'|'review'|'approved'|'rejected'|'executing'|'executed'|'failed';approvedBy?:string;executionErrorCode?:string;createdAt:string};

const db=()=>{if(!supabase)throw new Error('AI repository requires Supabase');return supabase};
const session=(row:Record<string,unknown>):ConversationSession=>({id:String(row.id),communityId:String(row.community_id),profileId:String(row.profile_id),goalId:row.goal_id?String(row.goal_id):undefined,title:String(row.title),status:row.status as ConversationSession['status'],createdAt:String(row.created_at),updatedAt:String(row.updated_at)});
const message=(row:Record<string,unknown>):ConversationMessage=>({id:String(row.id),communityId:String(row.community_id),sessionId:String(row.session_id),role:row.role as ConversationMessage['role'],content:String(row.content),reasoningSummary:row.reasoning_summary?String(row.reasoning_summary):undefined,proposal:row.proposal as Json|undefined,proposalStatus:row.proposal_status as ConversationMessage['proposalStatus'],approvedBy:row.approved_by?String(row.approved_by):undefined,executionErrorCode:row.execution_error_code?String(row.execution_error_code):undefined,createdAt:String(row.created_at)});

export async function listConversationSessions(communityId:string){const {data,error}=await db().from('ai_conversation_sessions').select('*').eq('community_id',communityId).order('updated_at',{ascending:false});if(error)throw error;return (data||[]).map(row=>session(row as Record<string,unknown>))}
export async function listConversationMessages(sessionId:string){const {data,error}=await db().from('ai_conversation_messages').select('*').eq('session_id',sessionId).order('created_at');if(error)throw error;return (data||[]).map(row=>message(row as Record<string,unknown>))}
export async function createConversationSession(input:{communityId:string;profileId:string;goalId?:string;title:string;contextSnapshot:Json}){const {data,error}=await db().from('ai_conversation_sessions').insert({community_id:input.communityId,profile_id:input.profileId,goal_id:input.goalId||null,title:input.title,context_snapshot:input.contextSnapshot}).select().single();if(error)throw error;return session(data as Record<string,unknown>)}
export async function appendConversationMessage(input:{communityId:string;sessionId:string;role:'user'|'assistant'|'system';content:string;reasoningSummary?:string;proposal?:Json}){const {data,error}=await db().from('ai_conversation_messages').insert({community_id:input.communityId,session_id:input.sessionId,role:input.role,content:input.content,reasoning_summary:input.reasoningSummary||null,proposal:input.proposal||null,proposal_status:input.proposal?'proposal':'none'}).select().single();if(error)throw error;return message(data as Record<string,unknown>)}
export async function reviewConversationProposal(messageId:string,decision:'approved'|'rejected'){const {data,error}=await db().rpc('review_ai_proposal',{p_message_id:messageId,p_decision:decision});if(error)throw error;return message(data as Record<string,unknown>)}
export async function recordUsage(input:{communityId:string;profileId:string;sessionId?:string;provider:string;model:string;operation:string;inputUnits:number;outputUnits:number;metadata?:Json}){const {error}=await db().from('ai_usage_events').insert({community_id:input.communityId,profile_id:input.profileId,session_id:input.sessionId||null,provider:input.provider,model:input.model,operation:input.operation,input_units:input.inputUnits,output_units:input.outputUnits,metadata:input.metadata||{}});if(error)throw error}
